os:
  - linux
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "10"
  - "node"
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
  - make travis
